name: payment_dialog
description: A customizable Flutter payment dialog with WebView for handling online payments.
version: 1.0.4
homepage: https://github.com/programmerhasan/payment_dialog
repository: https://github.com/programmerhasan/payment_dialog
issue_tracker: https://github.com/programmerhasan/payment_dialog/issues
documentation: https://pub.dev/packages/payment_dialog

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - payment
  - online-payment-gateways
  - customizable-dialog

screenshots:
  - description: "Payment Dialog Logo"
    path: screenshots/01.png

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  motion_toast: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/payment_loading.gif